---
#############################################################################
# Copyright 2020 Ramon Fischer                                              #
#                                                                           #
# Licensed under the Apache License, Version 2.0 (the "License");           #
# you may not use this file except in compliance with the License.          #
# You may obtain a copy of the License at                                   #
#                                                                           #
#     http://www.apache.org/licenses/LICENSE-2.0                            #
#                                                                           #
# Unless required by applicable law or agreed to in writing, software       #
# distributed under the License is distributed on an "AS IS" BASIS,         #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  #
# See the License for the specific language governing permissions and       #
# limitations under the License.                                            #
#############################################################################

- name: create group "steam"
  group:
    name: "steam"
    state: "present"
  tags:
    - l4d2_ds

- name: add user "steam" only for steam dedicated servers
  user:
    name: "steam"
    group: "steam"
    password: "!"
    shell: "/sbin/nologin"
    home: "/home/steam/"
    update_password: "on_create"
    create_home: "yes"
    state: "present"
  tags:
    - l4d2_ds

- name: prepare home directory
  file:
    path: "/home/steam/{{ item }}"
    owner: "steam"
    group: "steam"
    mode: "0700"
    state: "directory"
  with_items:
    - ".local/"
    - ".local/bin/"
    - ".local/etc/cronjobs/"
    - ".local/etc/steam/"
    - ".local/etc/steam/l4d2/"
    - ".local/etc/steam/l4d2/cfg/"
    - ".local/etc/steam/l4d2/cfg/userconfig/"
    - ".local/usr/share/steam/"
    - ".local/usr/share/steam/l4d2/"
  tags:
    - l4d2_ds

- name: prepare custom log directory
  file:
    path: "/var/log/{{ item.FILE_PATH }}"
    owner: "steam"
    group: "steam"
    mode: "{{ item.FILE_MODE }}"
    access_time: "preserve"
    modification_time: "preserve"
    state: "{{ item.FILE_STATE }}"
  with_items:
    - { FILE_PATH: "steam/",
        FILE_MODE: "0700",
        FILE_STATE: "directory" }
    - { FILE_PATH: "steam/l4d2-ds/",
        FILE_MODE: "0700",
        FILE_STATE: "directory" }
    - { FILE_PATH: "steam/steamcmd/",
        FILE_MODE: "0700",
        FILE_STATE: "directory" }
    - { FILE_PATH: "steam/steamcmd/steamcmd.log",
        FILE_MODE: "0640",
        FILE_STATE: "touch" }
  tags:
    - l4d2_ds

- name: create symlink to custom binary directory
  file:
    src: "/home/steam/.local/bin"
    dest: "/home/steam/bin"
    owner: "steam"
    group: "steam"
    state: "link"
  tags:
    - l4d2_ds

- name: create directory for repositories
  file:
    path: "/usr/local/share/{{ item }}"
    owner: "root"
    group: "root"
    mode: "0755"
    state: "directory"
  with_items:
    - "git/"
    - "git/keks24/"
  tags:
    - l4d2_ds

- name: clone repository "dotfiles"
  git:
    repo: "https://codeberg.org/keks24/dotfiles"
    dest: "/usr/local/share/git/keks24/dotfiles/"
    force: "yes"
  tags:
    - l4d2_ds

- name: create symlink for "bash" functions
  file:
    src: "/usr/local/share/git/keks24/dotfiles/usr/local/lib/functions.sh"
    dest: "/usr/local/lib/functions.sh"
    owner: "root"
    group: "root"
    state: "link"
  tags:
    - l4d2_ds

- name: copy steamcmd script
  template:
    src: "templates/home/steam/.local/usr/share/steam/l4d2/update_l4d2_ds.txt.j2"
    dest: "/home/steam/.local/usr/share/steam/l4d2/update_l4d2_ds.txt"
    owner: "steam"
    group: "steam"
    mode: "0644"
  tags:
    - l4d2_ds

- name: copy update shell script
  template:
    src: "templates/home/steam/bin/update_l4d2_ds.sh.j2"
    dest: "/home/steam/.local/bin/update_l4d2_ds.sh"
    owner: "steam"
    group: "steam"
    mode: "0755"
  tags:
    - l4d2_ds

- name: create symlink to update shell script for "cron"
  file:
    src: "/home/steam/.local/bin/update_l4d2_ds.sh"
    dest: "/home/steam/.local/etc/cronjobs/update_l4d2_ds.sh"
    owner: "steam"
    group: "steam"
    state: "link"
  tags:
    - l4d2_ds

- name: set up cronjob to update dedicated server
  cron:
    name: "update left 4 dead dedicated server every monday at 5am"
    minute: "0"
    hour: "5"
    day: "*"
    month: "*"
    weekday: "1"
    job: "/home/steam/.local/etc/cronjobs/update_l4d2_ds.sh --cronjob"
    user: "steam"
    state: "present"
  tags:
    - l4d2_ds

- name: allow "non-free" packages
  apt_repository:
    repo: "{{ item.APT_REPOSITORY_REPO }}"
    filename: "{{ item. APT_REPOSITORY_FILENAME }}"
    update_cache: "no"
    state: "present"
  with_items:
    - { APT_REPOSITORY_REPO: "deb http://ftp.debian.org/debian buster main non-free",
        APT_REPOSITORY_FILENAME: "ftp.debian.org_main" }
    - { APT_REPOSITORY_REPO: "deb http://ftp.debian.org/debian buster-updates main non-free",
        APT_REPOSITORY_FILENAME: "ftp.debian.org_updates" }
    - { APT_REPOSITORY_REPO: "deb http://security.debian.org buster/updates main non-free",
        APT_REPOSITORY_FILENAME: "security.debian.org_security" }
  tags:
    - l4d2_ds

- name: allow 32 bit packages, required for "steamcmd"
  shell: "/usr/bin/dpkg --add-architecture i386"
  args:
    creates: "/var/lib/dpkg/arch"
  tags:
    - l4d2_ds

- name: update package cache
  package:
    update_cache: "yes"
  tags:
    - l4d2_ds

- name: accept steam license agreement
  debconf:
    name: "steamcmd:i386"
    question: "steam/question"
    value: "I AGREE"
    vtype: "select"
  tags:
    - l4d2_ds

- name: install text-based steam client (steamcmd)
  package:
    name: "steamcmd:i386"
    state: "latest"
  tags:
    - l4d2_ds

# app list: https://developer.valvesoftware.com/wiki/Steam_Application_IDs
# dedicated servers list: https://developer.valvesoftware.com/wiki/Dedicated_Servers_List
- name: install and validate "left 4 dead 2 dedicated server"
  shell: "/usr/games/steamcmd +login anonymous +app_update 222860 validate +quit >> '/var/log/steam/steamcmd/steamcmd.log'"
  args:
    creates: "/home/steam/.steam/steamapps/common/Left 4 Dead 2 Dedicated Server/"
  become_user: "steam"
  tags:
    - l4d2_ds

- name: validate, if installation directory exists
  stat:
    path: "/home/steam/.steam/steamapps/common/Left 4 Dead 2 Dedicated Server/"
  register: "L4D2_DS_INSTALLATION_DIRECTORY"
  tags:
    - l4d2_ds

- name: prepare left 4 dead 2 log directory
  file:
    path: "/home/steam/.steam/steamapps/common/Left 4 Dead 2 Dedicated Server/left4dead2/logs"
    owner: "steam"
    group: "steam"
    mode: "0700"
    state: "directory"
  when:
    - L4D2_DS_INSTALLATION_DIRECTORY.stat.exists == true
  tags:
    - l4d2_ds

- name: create symlinks to steam log directories
  file:
    src: "/home/steam/.steam/{{ item.FILE_SRC }}"
    dest: "/var/log/steam/{{ item.FILE_DEST }}"
    owner: "steam"
    group: "steam"
    state: "link"
  with_items:
    - { FILE_SRC: "logs",
        FILE_DEST: "steamcmd/logs" }
    - { FILE_SRC: "steamapps/common/Left 4 Dead 2 Dedicated Server/left4dead2/logs",
        FILE_DEST: "l4d2-ds/logs" }
  tags:
    - l4d2_ds

- name: set up logrotate
  template:
    src: "{{ item }}"
    dest: "/etc/logrotate.d/{{ item | basename | regex_replace('\\.j2$') }}"
    owner: "root"
    group: "root"
    mode: "0644"
    validate: "/sbin/logrotate --debug %s"
  with_fileglob:
    - "templates/etc/logrotate.d/*.j2"
  tags:
    - l4d2_ds

- name: copy default file for systemd service unit
  template:
    src: "templates/etc/default/l4d2-ds.j2"
    dest: "/etc/default/l4d2-ds"
    owner: "root"
    group: "root"
    mode: "0600"
  tags:
    - l4d2_ds

- name: copy systemd service unit
  template:
    src: "templates/etc/systemd/system/l4d2-ds.service.j2"
    dest: "/etc/systemd/system/l4d2-ds.service"
    owner: "root"
    group: "root"
    mode: "0644"
  notify:
    - handler_enable_l4d2-ds
    - handler_start_l4d2-ds
  tags:
    - l4d2_ds

- name: create directory for systemd preset files
  file:
    path: "/etc/systemd/system-preset/"
    owner: "root"
    group: "root"
    mode: "0755"
    state: "directory"
  tags:
    - l4d2_ds

- name: copy systemd preset file
  template:
    src: "templates/etc/systemd/system-preset/99-custom.preset.j2"
    dest: "/etc/systemd/system-preset/99-custom.preset"
    owner: "root"
    group: "root"
    mode: "0644"
  tags:
    - l4d2_ds

- name: copy server configuration files
  template:
    src: "templates/home/steam/.local/etc/steam/l4d2/cfg/{{ item.TEMPLATE_SRC }}"
    dest: "/home/steam/.local/etc/steam/l4d2/cfg/{{ item.TEMPLATE_DEST }}"
    owner: "steam"
    group: "steam"
    mode: "0600"
  with_items:
      - { TEMPLATE_SRC: "server.cfg.j2",
          TEMPLATE_DEST: "server.cfg"}
      - { TEMPLATE_SRC: "userconfig/server.cfg.j2",
          TEMPLATE_DEST: "userconfig/server.cfg"}
      - { TEMPLATE_SRC: "userconfig/server.cfg.example.j2",
          TEMPLATE_DEST: "userconfig/server.cfg.example"}
  tags:
    - l4d2_ds

- name: create symlinks to server configuration files
  file:
    src: "/home/steam/.local/etc/steam/l4d2/cfg/{{ item.FILE_SRC }}"
    dest: "/home/steam/.steam/steamapps/common/Left 4 Dead 2 Dedicated Server/left4dead2/cfg/{{ item.FILE_DEST }}"
    owner: "steam"
    group: "steam"
    state: "link"
  with_items:
    - { FILE_SRC: "server.cfg",
        FILE_DEST: "server.cfg" }
    - { FILE_SRC: "userconfig",
        FILE_DEST: "userconfig" }
  tags:
    - l4d2_ds

- name: install tool to save "iptables" rules (iptables-persistent)
  package:
    name: "iptables-persistent"
    state: "latest"
  tags:
    - l4d2_ds

- name: prepare "iptables" configuration directory
  file:
    path: "/etc/{{ item.FILE_PATH }}"
    owner: "root"
    group: "root"
    mode: "{{ item.FILE_MODE }}"
    access_time: "preserve"
    modification_time: "preserve"
    state: "{{ item.FILE_STATE }}"
  with_items:
    - { FILE_PATH: "iptables",
        FILE_MODE: "0700",
        FILE_STATE: "directory" }
    - { FILE_PATH: "iptables/rules.v4",
        FILE_MODE: "0640",
        FILE_STATE: "touch" }
    - { FILE_PATH: "iptables/rules.v6",
        FILE_MODE: "0640",
        FILE_STATE: "touch" }
  tags:
    - l4d2_ds

- name: allow "127.0.0.1" on port "42000", drop incoming packages on port "42000"
  iptables:
    action: "append"
    chain: "INPUT"
    protocol: "tcp"
    source: "{{ item.IPTABLES_SOURCE }}"
    destination_port: "42000"
    jump: "{{ item.IPTABLES_JUMP }}"
    ip_version: "{{ item.IPTABLES_IP_VERSION }}"
    comment: "{{ ANSIBLE_MANAGED }}: steam netconsole (unencrypted)"
  with_items:
    - { IPTABLES_SOURCE: "127.0.0.1/32",
        IPTABLES_IP_VERSION: "ipv4",
        IPTABLES_JUMP: "ACCEPT" }
    - { IPTABLES_SOURCE: "0.0.0.0/0",
        IPTABLES_IP_VERSION: "ipv4",
        IPTABLES_JUMP: "DROP" }
    - { IPTABLES_SOURCE: "0:0:0:0:0:0:0:1/128",
        IPTABLES_IP_VERSION: "ipv6",
        IPTABLES_JUMP: "ACCEPT" }
    - { IPTABLES_SOURCE: "0:0:0:0:0:0:0:0/0",
        IPTABLES_IP_VERSION: "ipv6",
        IPTABLES_JUMP: "DROP" }
  notify:
    - "handler_enable_netfilter-persistent"
    - "handler_start_netfilter-persistent"
    - "handler_save_iptables"
    - "handler_validate_iptables"
  tags:
    - l4d2_ds

# refactor me: refactor this into a shell script, remove the pid file on "EXIT" signal
#              comment this, when the systemd service unit is finished
# "stdout" has to be redirected somewhere, in order to put the process in the background
# command line options: https://developer.valvesoftware.com/wiki/Command_Line_Options
#- name: start "left 4 dead 2 dedicated server"
#  shell: "./srcds_run -pidfile /var/tmp/l4d2-ds.pid -ip 0.0.0.0 -port 27015 -game left4dead2 +map c1m1_hotel >> /var/log/steam/l4d2-ds.log 2>> /var/log/steam/l4d2-ds_error.log &"
#  args:
#    chdir: "/home/steam/.steam/steamapps/common/Left 4 Dead 2 Dedicated Server/"
#    creates: "/var/tmp/l4d2-ds.pid"
#  become_user: "steam"
#  tags:
#    - l4d2_ds
